# Generated by Django 4.1.7 on 2023-02-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('link1', models.CharField(max_length=130)),
                ('link2', models.CharField(max_length=130)),
                ('web', models.CharField(max_length=130)),
            ],
        ),
    ]
